In [6]:
#!pip install numpy

In [7]:
import numpy as np
print(np.__version__)

2.2.5


In [10]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)

[1 2 3 4 5]
1


In [12]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [13]:
print(d.ndim)

3


In [14]:
print(d.shape)

(2, 2, 3)


In [15]:
range(0,4,1)

range(0, 4)

In [16]:
range(5)

range(0, 5)

In [19]:
for i in range(0,4,1):
    print(i)

0
1
2
3


In [20]:
for i in range(5):
    print(i)

0
1
2
3
4


In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]
